revoke all on function public.protect_profile_privileges() from public, anon, authenticated;
revoke all on function public.handle_new_user() from public, anon, authenticated;
revoke all on function public.handle_swipe_match() from public, anon, authenticated;
revoke all on function public.effective_tier(uuid) from public, anon;
revoke all on function public.has_role(uuid, public.app_role) from public, anon;
revoke all on function public.is_super_admin() from public, anon;
revoke all on function public.in_conversation(uuid, uuid) from public, anon;
grant execute on function public.effective_tier(uuid) to authenticated;
grant execute on function public.has_role(uuid, public.app_role) to authenticated;
grant execute on function public.is_super_admin() to authenticated;
grant execute on function public.in_conversation(uuid, uuid) to authenticated;